-- TIPOS DE DADOS EM SQL
1- BOOLEANOS (TRUE OR FALSE) INICIADO COMO NULL
É REPRESENTADO POR BIT

2- CARACTERE
Se vc define que seu char é 50, e voce nao usa esses 50 ele ocupa tudo


Tamanho fixo - CHAR
TAMANHO VARIADO = VARCHAR OU NVARCHAR

No caso é parecido com o char de tamanho fixo, porem se vc usar apenas 10 
por exemplo ele vai preencher apenas os 10, entao é variado




3- NUMERO
Valores exatos
TINYINT = SAO VALORES INTEIROS 4  - 5  -  6 -  12
SMALLINT = MESMA COISA POREM COM LIMITE MAIOR
INT = MESMA COISA POREM COM LIMITE MAIOR
BIGINT = MESMA COISA POREM COM LIMITE MAIOR

NUMERIC OU DECIMAL - VALORES EXATOS, MAS PERMITE TER PARTE FRACIONADAS
PODEM SER ESPECIFICADOS EM PRECISAO E ESCALA
ESCALA É O NUMERO DE DIGITOS
PRECISAO É QUANTOS VALORES ELE TEM

113,44 == 5 DIGITOS (ESCALA), E 2 VALORES APOS === NUMERIC(5,2)

VALORES APROXIMADOS
REAL - TEM PRECISAO APROXIMADA ATÉ 15 DIGITOS
FLOAT = MESMO CONCEITO DO REAL


4 - TEMPORAIS
DATE - ARMAZENA DATA NO FORMADO AAAA/MM/DD
DATETIME = ARMAZENA DATA E HORA NO FORMADO   AAAA/MM/DD:HH/MM/SS
DATETIME2 - DATA HORA E COM ADICAO DE MILISEGUNDOS AAAA/MM/DD:HH/MM/SS:SSSS
SMALLDATETIME - DATA E HORA RESPEITANDO O TEMPO LIMITE DE '1900-01-01:00:00:00' ATE '2000-01-01:00:00:00'  ###NAO ARMAZENA MILISEGUNDOS
TIME - HOTAS MINUTOS SEGUNDOS E MILISEGUNDOS
DATETIMEOFFSET - PERMITE ARMAZENAS HORAS E DATAS INCLUINDO FUSOHORARIO


