----CREATE TABLE 

----CREATE TABLE nomeTabela (
----	coluna1 tipo restricaoDaColuna (se houver),
----	coluna1 tipo restricaoDaColuna (se houver)
----)

--ALGUMAS RESTRICOES DO SQL - 
--NOT NULL - NAO PERMITE VALORES NULOS
--UNIQUE - NAO PERMITE QUE OS VALORES SEJAM IGUAIS
--PRIMARY KEY - UMA JUNCAO DE NOT NULL E UNIQUE = NAO PODE TER NULOS E IGUAIS
--FOREIGN KEY - IDENTIFICA UNICAMENTE UMA LINHA EM OUTRA TABELA
--CHECK - FORÇA UMA CONDICAO ESPECIFICA EM UMA TABELA
--DEFAULT - FORCA UM VALOR PADRAO QUANDO NENHUM VALOR É PASSADO


CREATE TABLE Canal (
	ChannelID int Primary Key,
	Name varchar(150) NOT NULL,
	Subscribers INT DEFAULT 0,
	DateCreate DATETIME NOT NULL
)

CREATE TABLE Video (
	VideoID INT PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Views INT DEFAULT 0,
	Likes INT DEFAULT 0,
	Dislikes INT DEFAULT 0,
	Duration INT NOT NULL,
	CanalID	INT FOREIGN KEY REFERENCES Canal(ChannelID),
)

SELECT * FROM Video