--INSERT INTO NOMETABELA(COLUNA1, COLUNA2....)
--VALUES (VALOR1, VALOR2)

--SIGNIFICA - INSERIR NA COLUNA 2 E 3 ESSES VALORES>:
--VALOR 1 E VALOR 2


--INSERIR INFO DE OUTRAS TABELAS EM UMA TABELA EXISTENTE:
--INSERT INTO TABELAA(COLUNA1)
--SELECT COLUNA2
--FROM TABELAB



CREATE TABLE Address (
	NameID INT PRIMARY KEY,
	Name VARCHAR(150),
	LastName VARCHAR(150),
	Address VARCHAR(150) NOT NULL,
	State VARCHAR(150) NOT NULL,
	Age INT DEFAULT 0
)

ALTER TABLE Address ADD LastName VARCHAR(150)
EXEC sp_rename 'Address.City', 'State', 'COLUMN';




SELECT * FROM Address

INSERT INTO Address(NameID, Name, LastName, Address, State, Age)
VALUES (2335416, 'Joao', 'Freire', 'Santa barbara D Oeste', 'São Paulo', 24)