---- UPDATE
----SERVE PRA ATUALIZAR LINHAS DO BANCO DE DADOS

--UPDATE NOMETABELA
--SET COLUNA1 = VALOR2  -- TROCAR O VALOR DA COLUNA 1 PELO VALOR 2
--	COLUNA 2 = VALO2 -- PODE SER PASSADO MAIS DE UM
--WHERE CONDICAO -- SE VOCE NAO PASSAR UM WHERE VC VAI ALTERAR TODOS OS DADOS
CREATE TABLE aula(
	id INT PRIMARY KEY,
	Name VARCHAR(20) NOT NULL
)


INSERT INTO aula(id, name)
VALUES
(1, 'aula 1'),
(2, 'aula 2'),
(3, 'aula 3'),
(4, 'aula 4'),


UPDATE aula
SET Name = 'Jair Messias'
WHERE id = 2


SELECT * FROM AULA