-- ALTER TABLE
-- APRENDER A ALTERAR A ESTRUTURA DE UMA TABELA

--ALTER TABLE nomeDaTabela
--ACAO

--PODEMOS :
--ADCIONAR REMOVER ALTERAR COLUNA
--SETAR VALORES PADROES PARA COLUNA
--ADD OU REMOVER RESTRICOES DE COLUNAS
--RENOMEAR UMA TABELA


CREATE TABLE youtube (
	id int PRIMARY KEY,
	name VARCHAR(150) NOT  NULL unique,
	Category VARCHAR(150) NOT NULL,
	DateCreate DATETIME NOT NULL
)

SELECT * FROM YOUTUBE



ALTER TABLE youtube
add active bit

ALTER TABLE youtube
ALTER COLUMN Category VARCHAR(300) NOT NULL


EXEC sp_RENAME 'nomeTabela.nomeColunaAtual', 'nomeColunanova', 'COLUMN'

EXEC sp_RENAME 'youtube.id', 'ChannelID', 'COLUMN'


CREATE TABLE netflix(
	ListID INT PRIMARY KEY,
	Terror VARCHAR(150) NOT NULL UNIQUE,
	Drama VARCHAR(150) NOT NULL UNIQUE,
	Suspense VARCHAR(150) NOT NULL UNIQUE,
)


SELECT * FROM streaming


--ALTERAR TIPO DE UMA COLUNA
ALTER TABLE netflix
ALTER COLUMN Terror VARCHAR(200) NOT NULL

-- RENOMEAR O NOME DE UMA COLUNA
EXEC sp_RENAME 'netflix.Terror', 'Terror Psicologico'

--RENOMEIE O NOME DA TABELA QUE VOCE CRIOU
EXEC sp_RENAME 'netflix', 'streaming'