--DROP TABLE
--COMO EXCLUIR UMA TABELA DE BANCO DE DADOS
-- NAO PODEMOS DROPAR TABELAS REFERENCIADAS POR OUTRAS

DROP TABLE youtube


--APAGAR APENAS O CONTEUDO DA TABELA E NAO A TABELA EM SI

--TRUNCATE TABLE youtube

--VAI LIMPAR TUDO e deixar sem informacao

