--NOT NULL CONSTRAINT

--VAMOS USAR ESSA SITUACAO ONDE TODOS OS VALORES PRECISAM SER PREENCHIDOS
--


CREATE TABLE carteiraMotorista(
	id int NOT NULL,
	nome varchar(150) NOT NULL,
	Idade INT CHECK (idade >= 18)  -- vai checar se a idade � maior que 18, se nao da erro
)



--UNIQUE CONSTRAINT

--ELA NAO É UMA PRIMARY KEY POIS PODEM TER VARIAS EM UMA TABELA
--IMPOSSIBILITANDO VALORES IGUAIS NAS COLUNAS

-- nome varchar(150) NOT NULL UNIQUE,


--VIEWS
--SERVE PRA FAZER UMA CONSULTA ESPECIFICA DE UMA TABELA

CREATE VIEW NomeView AS
SELECT FirstName, MiddleName
FROM Person.Person
WHERE Title = 'Ms.';


SELECT * FROM NomeView